### ISSUE TITLE
minknow_api RPC error 

### ISSUE THREAD

**Issue by ccr25** [nanoporetech/minknow_api#39]
Hi,

I have been running the program uncalled with minknow successfully for the past several months on Ubuntu 20.04. After a round of updates, I now get the following error message:

uncalled realtime reference_genomes/Ames/genome.fasta -t 10 --enrich --full -c 3 | tee test.paf
[15:23:21 - ReadUntil] Creating many chunk client with ReadCache data queue filtering to strand2, strand1, and strand read chunks.
[15:23:21 - ReadUntil] Using pre-defined read classification map.
[15:23:21 - ReadUntil] Creating rpc connection on port 8000.
[15:23:21 - minknow_api] Error received from rpc
[15:23:21 - minknow_api] Failed to connect to minknow instance (retry 1/5): failed to connect to all addresses
[15:23:22 - minknow_api] Error received from rpc
[15:23:22 - minknow_api] Failed to connect to minknow instance (retry 2/5): failed to connect to all addresses
[15:23:24 - minknow_api] Error received from rpc
[15:23:24 - minknow_api] Failed to connect to minknow instance (retry 3/5): failed to connect to all addresses
[15:23:26 - minknow_api] Error received from rpc
[15:23:26 - minknow_api] Failed to connect to minknow instance (retry 4/5): failed to connect to all addresses
[15:23:29 - minknow_api] Error received from rpc
[15:23:29 - minknow_api] Failed to connect to minknow instance (retry 5/5): failed to connect to all addresses
Traceback (most recent call last):
File "/home/jason/.local/lib/python3.8/site-packages/uncalled-2.2-py3.8-linux-x86_64.egg/EGG-INFO/scripts/uncalled", line 195, in realtime_cmd
client = unc.minknow_client.Client(conf.host, conf.port, conf.chunk_time, conf.num_channels)
File "/home/jason/.local/lib/python3.8/site-packages/uncalled-2.2-py3.8-linux-x86_64.egg/uncalled/minknow_client.py", line 43, in init
read_until.ReadUntilClient.init(
File "/home/jason/anaconda3/envs/pima/lib/python3.8/site-packages/read_until/base.py", line 255, in init
self.connection = minknow_api.Connection(host=self.mk_host, port=self.grpc_port)
File "/home/jason/anaconda3/envs/pima/lib/python3.8/site-packages/minknow_api/init.py", line 327, in init
raise error
File "/home/jason/anaconda3/envs/pima/lib/python3.8/site-packages/minknow_api/init.py", line 299, in init
self.instance.get_version_info()
File "/home/jason/anaconda3/envs/pima/lib/python3.8/site-packages/minknow_api/instance_service.py", line 93, in get_version_info
return run_with_retry(self._stub.get_version_info,
File "/home/jason/anaconda3/envs/pima/lib/python3.8/site-packages/minknow_api/instance_service.py", line 37, in run_with_retry
result = MessageWrapper(method(message, timeout=timeout), unwraps=unwraps)
File "/home/jason/anaconda3/envs/pima/lib/python3.8/site-packages/grpc/_channel.py", line 946, in call
return _end_unary_response_blocking(state, call, False, None)
File "/home/jason/anaconda3/envs/pima/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
status = StatusCode.UNAVAILABLE
details = "failed to connect to all addresses"
debug_error_string = "{"created":"@1652912609.827260489","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1652912609.827259173","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"

It has been working great so I think the latest update is making it crash. Any ideas what I need to change? Thanks,

Chandler

**Comment by jorj1988** [comment]
Hi @ccr25 ,

What version were you running, and what are you now running?

It may be that the new version of minknow is expecting you to authenticate - if youre connecting to minknow remotely (from a different computer to where the sequencing is running).

You _can_ disable this and achieve the older behaviour - but there are risks to this.

If you can get back to me about the versions I can be a bit more specific!

Thanks,
- George

**Comment by ccr25** [comment]
Hi George, 

I am currently running minknow_api version 4.2.4. I do not know what version I was running previously. I am running minknow version 22.03.6 which includes MinKNOW core 5.0.0, Guppy 6.0.7, Bream 7.0.9, and Script Configuration 5.0.8. I am connecting to minknow on the computer that the sequencing is happening. Thanks, 

Chandler

**Comment by jorj1988** [comment]
Hi @ccr25 , API version 4.2.4 is for use with MinKNOW 21.02.

You will need to upgrade your MinKNOW API version inline with your MinKNOW version - so to at least 5.0 (You should be within the same major version).

Given you are connecting to minknow from the sequencer itself, I would expect the upgrade to solve the problem on its own - but let me know if it doesn't.

Thanks,
George
